/*
 * Copyright 2025 Yubico AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

use std::fmt;
use std::fmt::Display;
use strum_macros::EnumIter;
use serde::{Deserialize, Serialize};
use base64::{engine::general_purpose::STANDARD_NO_PAD, Engine};
use gf256::shamir::shamir;
use yubihsmrs::object::{ObjectAlgorithm, ObjectCapability, ObjectDescriptor, ObjectDomain, ObjectHandle, ObjectType};
use yubihsmrs::Session;
use crate::traits::operation_traits::YubihsmOperations;
use crate::traits::command_traits::Command;
use crate::common::error::MgmError;
use crate::common::algorithms::MgmAlgorithm;
use crate::common::types::{NewObjectSpec, EXIT_LABEL};
use crate::common::util::{contains_all, get_object_descriptors};
use crate::hsm_operations::asym::AsymmetricOperations;
use crate::hsm_operations::sym::SymmetricOperations;


// 2 object ID bytes + 2 domains bytes + 8 capabilities bytes + 8 delegated capabilities = 20 bytes
static WRAP_SPLIT_PREFIX_LEN: usize = 20;

#[derive(Debug, Clone, Copy, PartialEq, Eq, EnumIter)]
pub enum WrapCommand {
    List,
    GetKeyProperties,
    Generate,
    Import,
    Delete,
    GetPublicKey,
    ExportWrapped,
    ImportWrapped,
    GetRandom,
    Exit,
}

impl Command for WrapCommand {
    fn label(&self) -> &'static str {
        match self {
            Self::List => "List",
            Self::GetKeyProperties => "Get Object Properties",
            Self::Generate => "Generate Wrap Key",
            Self::Import => "Import Wrap Key",
            Self::Delete => "Delete Wrap Key",
            Self::GetPublicKey => "Get Public Key",
            Self::ExportWrapped => "Export objects under wrap",
            Self::ImportWrapped => "Import wrapped object",
            Self::GetRandom => "Generate pseudo random number",
            Self::Exit => EXIT_LABEL,
        }
    }

    fn description(&self) -> &'static str {
        match self {
            Self::List => "List all wrap keys stored on the YubiHSM",
            Self::GetKeyProperties => "Get properties of a wrap key stored on the YubiHSM",
            Self::Generate => "Generate a new wrap key inside the YubiHSM",
            Self::Import => "Import a wrap key into the YubiHSM",
            Self::Delete => "Delete a wrap key from the YubiHSM",
            Self::GetPublicKey => "Retrieve the public key portion of an RSA wrap key stored on the YubiHSM",
            Self::ExportWrapped => "Writes files ending with .yhw to specified directory",
            Self::ImportWrapped => "Import wrapped object from a .yhw file",
            Self::GetRandom => "Get pseudo random bytes generated by the YubiHSM",
            Self::Exit => "Exit YubiHSM Manager",
        }
    }

    fn required_capabilities(&self) -> &'static [ObjectCapability] {
        match self {
            Self::List | Self::GetKeyProperties | Self::Exit => &[],
            Self::Generate => &[ObjectCapability::GenerateWrapKey],
            Self::Import => &[ObjectCapability::PutWrapKey, ObjectCapability::PutPublicWrapKey],
            Self::Delete => &[ObjectCapability::DeleteWrapKey, ObjectCapability::DeletePublicWrapKey],
            Self::GetPublicKey => &[],
            Self::ExportWrapped => &[ObjectCapability::ExportWrapped],
            Self::ImportWrapped => &[ObjectCapability::ImportWrapped],
            Self::GetRandom => &[ObjectCapability::GetPseudoRandom],
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum WrapKeyType {
    #[default]
    Aes,
    Rsa,
    RsaPublic,
}

pub struct WrapKeyShares {
    pub shares: u8,
    pub threshold: u8,
    pub shares_data: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum WrapType {
    #[default]
    Object,
    Key,
}

impl Display for WrapType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            WrapType::Object => write!(f, "YubiHSM2 Object"),
            WrapType::Key => write!(f, "Key data only"),
        }
    }
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct WrapOpSpec {
    pub wrapkey_id: u16,
    pub wrapkey_type: WrapKeyType,
    pub wrap_type: WrapType,
    pub include_ed_seed: bool,
    pub aes_algorithm: Option<ObjectAlgorithm>,
    pub oaep_algorithm: Option<ObjectAlgorithm>,
    pub mgf1_algorithm: Option<ObjectAlgorithm>,
}

pub struct WrappedData {
    pub object_id: u16,
    pub object_type: ObjectType,
    pub wrapkey_id: u16,
    pub wrapped_data: Vec<u8>,
    pub error: Option<MgmError>,
}

const AES_WRAP_KEY_CAPABILITIES: [ObjectCapability; 3] = [
    ObjectCapability::ExportWrapped,
    ObjectCapability::ImportWrapped,
    ObjectCapability::ExportableUnderWrap,
];

const RSA_WRAP_KEY_CAPABILITIES: [ObjectCapability; 2] = [
    ObjectCapability::ImportWrapped,
    ObjectCapability::ExportableUnderWrap,
];

const PUBLIC_WRAP_KEY_CAPABILITIES: [ObjectCapability; 2] = [
    ObjectCapability::ExportWrapped,
    ObjectCapability::ExportableUnderWrap,
];

pub struct WrapOperations;

impl YubihsmOperations for WrapOperations {

    fn context(&self) -> &'static str {
        WrapOperations::WRAP_CONTEXT
    }

    fn get_all_objects(&self, session: &Session) -> Result<Vec<ObjectDescriptor>, MgmError> {
        let mut keys = session.list_objects_with_filter(
            0, ObjectType::WrapKey, "", ObjectAlgorithm::ANY, &Vec::new())?;
        keys.extend_from_slice(&session.list_objects_with_filter(
            0, ObjectType::PublicWrapKey, "", ObjectAlgorithm::ANY,
            &Vec::new())?);
        get_object_descriptors(session, &keys)
    }

    fn get_generation_algorithms(&self) -> Vec<MgmAlgorithm> {
        MgmAlgorithm::WRAP_KEY_ALGORITHMS.to_vec()
    }

    fn get_object_capabilities(
        &self,
        object_type: Option<ObjectType>,
        object_algorithm: Option<ObjectAlgorithm>) -> Result<Vec<ObjectCapability>, MgmError> {

        if object_type.is_none() || object_algorithm.is_none() {
            return Err(MgmError::InvalidInput(
                "Missing object type and/or object algorithm".to_string(),
            ));
        }

        let key_type = Self::get_wrapkey_type(
            &object_type.unwrap(),
            &object_algorithm.unwrap(),
        )?;

        match key_type {
            WrapKeyType::Aes => Ok(AES_WRAP_KEY_CAPABILITIES.to_vec()),
            WrapKeyType::Rsa => Ok(RSA_WRAP_KEY_CAPABILITIES.to_vec()),
            WrapKeyType::RsaPublic => Ok(PUBLIC_WRAP_KEY_CAPABILITIES.to_vec()),
        }
    }

    fn generate(&self, session: &Session, spec: &NewObjectSpec) -> Result<u16, MgmError> {
        let id = session
            .generate_wrap_key(
                spec.id,
                &spec.label,
                &spec.domains,
                &spec.capabilities,
                spec.algorithm,
                &spec.delegated_capabilities)?;
        Ok(id)
    }

    fn import(&self, session: &Session, spec: &NewObjectSpec) -> Result<u16, MgmError> {
        let id = match spec.object_type {
            ObjectType::WrapKey => session.import_wrap_key(
                spec.id,
                &spec.label,
                &spec.domains,
                &spec.capabilities,
                spec.algorithm,
                &spec.delegated_capabilities,
                &spec.data[0])?,
            ObjectType::PublicWrapKey => session.import_public_wrap_key(
                spec.id,
                &spec.label,
                &spec.domains,
                &spec.capabilities,
                spec.algorithm,
                &spec.delegated_capabilities,
                &spec.data[0])?,
            _ => {
                return Err(MgmError::InvalidInput(
                    "ImportObjectSpec has invalid object type for wrap key".to_string(),
                ));
            }
        };
        Ok(id)    }
}

impl WrapOperations {

    pub const WRAP_CONTEXT: &'static str = "wrap";

    pub fn get_algorithm_from_keylen(keylen: usize) -> Result<ObjectAlgorithm, MgmError> {
        match keylen {
            16 => Ok(ObjectAlgorithm::Aes128CcmWrap),
            24 => Ok(ObjectAlgorithm::Aes192CcmWrap),
            32 => Ok(ObjectAlgorithm::Aes256CcmWrap),
            256 => Ok(ObjectAlgorithm::Rsa2048),
            384 => Ok(ObjectAlgorithm::Rsa3072),
            512 => Ok(ObjectAlgorithm::Rsa4096),
            _ => Err(MgmError::Error(format!("Unsupported key length {}", keylen))),
        }
    }

    pub fn get_wrapkey_type(object_type: &ObjectType, algorithm: &ObjectAlgorithm) -> Result<WrapKeyType, MgmError> {
        match object_type {
            ObjectType::PublicWrapKey => Ok(WrapKeyType::RsaPublic),
            ObjectType::WrapKey => match algorithm {
                ObjectAlgorithm::Aes128CcmWrap |
                ObjectAlgorithm::Aes192CcmWrap |
                ObjectAlgorithm::Aes256CcmWrap => Ok(WrapKeyType::Aes),
                ObjectAlgorithm::Rsa2048 |
                ObjectAlgorithm::Rsa3072 |
                ObjectAlgorithm::Rsa4096 => Ok(WrapKeyType::Rsa),
                _ => {
                    Err(MgmError::InvalidInput(
                        "Unsupported algorithm for wrap key".to_string(),
                    ))
                }
            },
            _ => Err(MgmError::InvalidInput(
                "Unsupported object type for wrap key".to_string(),
            )),
        }
    }

    fn get_wrapkeys_by_type(session:&Session, key_type:WrapKeyType) -> Result<Vec<ObjectDescriptor>, MgmError> {
        if key_type == WrapKeyType::RsaPublic {
            let keys = session.list_objects_with_filter(
                0, ObjectType::PublicWrapKey, "", ObjectAlgorithm::ANY,
                &Vec::new())?;
            Ok(get_object_descriptors(session, keys.as_slice())?)
        } else {
            let keys = session.list_objects_with_filter(
                0, ObjectType::WrapKey, "", ObjectAlgorithm::ANY, &Vec::new())?;
            let mut keys = get_object_descriptors(session, keys.as_slice())?;
            if key_type == WrapKeyType::Aes {
                keys.retain(|k| !AsymmetricOperations::is_rsa_key_algorithm(k.algorithm()));
            } else if key_type == WrapKeyType::Rsa {
                keys.retain(|k| AsymmetricOperations::is_rsa_key_algorithm(k.algorithm()));
            }
            Ok(keys)
        }
    }

    pub fn get_rsa_wrapkeys(session:&Session) -> Result<Vec<ObjectDescriptor>, MgmError> {
        let mut keys = Self.get_all_objects(session)?;
        keys.retain(|k| AsymmetricOperations::is_rsa_key_algorithm(k.algorithm()));
        Ok(keys)
    }

    pub fn get_wrapping_keys(session:&Session, authkey: &ObjectDescriptor) -> Result<Vec<ObjectDescriptor>, MgmError> {
        if !authkey.capabilities().contains(&ObjectCapability::ExportWrapped) {
            return Ok(Vec::new());
        }
        let mut keys = Self::get_wrapkeys_by_type(session, WrapKeyType::Aes)?;
        keys.extend_from_slice(&Self::get_wrapkeys_by_type(session, WrapKeyType::RsaPublic)?);
        keys.retain(|k| k.capabilities().contains(&ObjectCapability::ExportWrapped));
        if keys.is_empty() {
            return Err(MgmError::Error(
                format!("No wrap keys with {:?} capability were found", ObjectCapability::ExportWrapped)));
        }
        Ok(keys)
    }

    pub fn get_unwrapping_keys(session:&Session, authkey: &ObjectDescriptor) -> Result<Vec<ObjectDescriptor>, MgmError> {
        if !authkey.capabilities().contains(&ObjectCapability::ImportWrapped) {
            return Ok(Vec::new());
        }
        let mut keys = Self::get_wrapkeys_by_type(session, WrapKeyType::Aes)?;
        keys.extend_from_slice(&Self::get_wrapkeys_by_type(session, WrapKeyType::Rsa)?);
        keys.retain(|k| k.capabilities().contains(&ObjectCapability::ImportWrapped));
        if keys.is_empty() {
            return Err(MgmError::Error(
                format!("No wrap keys with {:?} capability were found", ObjectCapability::ImportWrapped)));
        }
        Ok(keys)
    }

    pub fn get_exportable_objects(session: &Session, wrap_key: &ObjectDescriptor, wrap_type: WrapType) -> Result<Vec<ObjectDescriptor>, MgmError> {
        if wrap_key.delegated_capabilities().is_none() {
            return Ok(Vec::new());
        }
        let delegated = wrap_key.delegated_capabilities().as_ref().unwrap();

        let objects = session.list_objects_with_filter(
            0,
            ObjectType::Any,
            "",
            ObjectAlgorithm::ANY,
            &[ObjectCapability::ExportableUnderWrap])?;
        let mut objects = get_object_descriptors(session, objects.as_slice())?;
        objects.retain(|obj| contains_all(delegated, obj.capabilities()));
        objects.retain(|obj| wrap_key.domains().iter().any(|d| obj.domains().contains(d)));
        if wrap_type == WrapType::Key {
            objects.retain(|obj| obj.object_type() == &ObjectType::AsymmetricKey || obj.object_type() == &ObjectType::SymmetricKey);
        }
        Ok(objects)
    }

    pub fn get_rsa_unwrapped_key_algorithms() -> Vec<MgmAlgorithm> {
        let mut algos = Vec::new();
        algos.extend_from_slice(AsymmetricOperations.get_generation_algorithms().as_slice());
        algos.extend_from_slice(SymmetricOperations.get_generation_algorithms().as_slice());
        algos
    }

    pub fn split_wrap_key(wrap_key:&NewObjectSpec, threshold:u8, shares:u8) -> Result<WrapKeyShares, MgmError> {
        let mut split_key = WrapKeyShares {
            shares,
            threshold,
            shares_data: Vec::new(),
        };

        let mut data = Vec::<u8>::new();
        data.push(((wrap_key.id >> 8) & 0xff) as u8);
        data.push((wrap_key.id & 0xff) as u8);
        data.append(&mut ObjectDomain::bytes_from_slice(wrap_key.domains.as_slice()));
        data.append(&mut ObjectCapability::bytes_from_slice(wrap_key.capabilities.as_slice()));
        data.append(&mut ObjectCapability::bytes_from_slice(wrap_key.delegated_capabilities.as_slice()));
        data.extend_from_slice(wrap_key.data[0].as_slice());

        let raw_shares = vsss_rs::Gf256::split_array(
            threshold as usize,
            shares as usize,
            &data,
            rand::rngs::OsRng,
        )?;

        split_key.shares_data = raw_shares
            .iter()
            .map(|share| {
                format!("{}-{}-{}", threshold, share[0], hex::encode(&share[1..]))
            })
            .collect();

        Ok(split_key)
    }

    pub fn get_wrapkey_from_shares(shares: Vec<String>) -> Result<NewObjectSpec, MgmError> {

        let parsed = shares[0].split('-').collect::<Vec<&str>>();
        let threshold: usize = parsed[0].parse().map_err(|_| MgmError::InvalidInput("Invalid share format".to_string()))?;
        if (shares.len()) < threshold {
            return Err(MgmError::InvalidInput(format!("Not enough shares provided. At least {} shares are required", threshold)));
        }

        let secret = if hex::decode(parsed[2]).is_ok() { // New style shares with hex-encoded data
            let vsss_shares: Vec<Vec<u8>> = shares.iter().map(|s| {
                let parts: Vec<&str> = s.trim().split('-').collect();
                let Ok(share_id) = parts[1].parse::<u8>() else {
                    return Err(MgmError::InvalidInput(format!("Unable to parse share ID: {}", s)));
                };
                let share_data = hex::decode(parts[2])?;
                let mut share = Vec::with_capacity(1 + share_data.len());
                share.push(share_id);
                share.extend_from_slice(&share_data);
                Ok(share)
            }).collect::<Result<Vec<_>, MgmError>>()?;

            vsss_rs::Gf256::combine_array(&vsss_shares)?
        } else { // Legacy shares obtained from yubihsm-setup
            let gf256_shares: Vec<Vec<u8>> = shares.iter().map(|s| Self::rusty_share_to_gf256_share(s)).collect();

            shamir::reconstruct(&gf256_shares)
        };

        if secret.len() < WRAP_SPLIT_PREFIX_LEN {
            return Err(MgmError::InvalidInput("Reconstructed wrap key share data is too short".to_string()));
        }

        let key_len = secret.len() - WRAP_SPLIT_PREFIX_LEN;

        let mut wrapkey_spec = NewObjectSpec::default();
        wrapkey_spec.object_type = ObjectType::WrapKey;
        wrapkey_spec.algorithm = WrapOperations::get_algorithm_from_keylen(key_len)?;
        wrapkey_spec.id = ((u16::from(secret[0])) << 8) | u16::from(secret[1]);
        wrapkey_spec.domains = ObjectDomain::from_bytes(&secret[2..4])?;
        wrapkey_spec.capabilities = ObjectCapability::from_bytes(&secret[4..12])?;
        wrapkey_spec.delegated_capabilities = ObjectCapability::from_bytes(&secret[12..20])?;

        wrapkey_spec.data.push(secret[20..].to_vec());

        Ok(wrapkey_spec)
    }

    pub fn export_wrapped(session: &Session, wrap_op_spec: &WrapOpSpec, export_objects: &Vec<ObjectHandle>) -> Result<Vec<WrappedData>, MgmError> {
        let mut wrapped = Vec::new();
        for object in export_objects {
            let mut w = WrappedData {
                object_id: object.object_id,
                object_type: object.object_type,
                wrapkey_id: wrap_op_spec.wrapkey_id,
                wrapped_data: Vec::new(),
                error: None,
            };

            let res = match wrap_op_spec.wrapkey_type {
                WrapKeyType::Aes => {
                    let format: u8 = if wrap_op_spec.include_ed_seed { 1 } else { 0 };
                    session.export_wrapped_ex(wrap_op_spec.wrapkey_id, object.object_type, object.object_id, format)
                },
                WrapKeyType::RsaPublic => {
                    let aes_algo = match wrap_op_spec.aes_algorithm {
                        Some(algo) => algo,
                        None => ObjectAlgorithm::Aes256,
                    };

                    let oaep_algo = match wrap_op_spec.oaep_algorithm {
                        Some(algo) => algo,
                        None => ObjectAlgorithm::RsaOaepSha256,
                    };

                    let oaep_label = Self::get_oaep_label(&oaep_algo)?;
                    let mgf1_algo = match wrap_op_spec.mgf1_algorithm {
                        Some(algo) => algo,
                        None => ObjectAlgorithm::Mgf1Sha256,
                    };

                    match wrap_op_spec.wrap_type {
                        WrapType::Object => session.export_rsa_wrapped_object(
                            wrap_op_spec.wrapkey_id,
                            object.object_type,
                            object.object_id,
                            aes_algo,
                            oaep_algo,
                            mgf1_algo,
                            &oaep_label,
                        ),
                        WrapType::Key => session.export_rsa_wrapped_key(
                            wrap_op_spec.wrapkey_id,
                            object.object_type,
                            object.object_id,
                            aes_algo,
                            oaep_algo,
                            mgf1_algo,
                            &oaep_label,
                        ),
                    }
                },
                WrapKeyType::Rsa => {
                    return Err(MgmError::InvalidInput("Private RSA key cannot be used for wrapping".to_string()))
                }
            };

            match res {
                Ok(bytes) => w.wrapped_data = bytes,
                Err(err) => w.error = Some(MgmError::LibYubiHsm(err))
            }
            wrapped.push(w);
        }
        Ok(wrapped)
    }

    pub fn import_wrapped(session: &Session, wrap_op_spec: &WrapOpSpec, wrapped: &[u8], new_key_spec: Option<NewObjectSpec>) -> Result<ObjectHandle, MgmError> {
        let data = wrapped.to_vec();

        let handle = match wrap_op_spec.wrapkey_type {
            WrapKeyType::Aes => session.import_wrapped(wrap_op_spec.wrapkey_id, &data)?,
            WrapKeyType::Rsa => {
                let oaep_algo = match wrap_op_spec.oaep_algorithm {
                    Some(algo) => algo,
                    None => ObjectAlgorithm::RsaOaepSha256,
                };
                let oaep_label = Self::get_oaep_label(&oaep_algo)?;
                let mgf1_algo = match wrap_op_spec.mgf1_algorithm {
                    Some(algo) => algo,
                    None => ObjectAlgorithm::Mgf1Sha256,
                };
                match wrap_op_spec.wrap_type {
                    WrapType::Object => session.import_rsa_wrapped_object(
                        wrap_op_spec.wrapkey_id,
                        oaep_algo,
                        mgf1_algo,
                        &oaep_label,
                        &data,
                    )?,
                    WrapType::Key => {
                        if new_key_spec.is_none() {
                            return Err(MgmError::InvalidInput("Object parameters for the imported wrapped key is missing".to_string()));
                        }
                        let key_spec = new_key_spec.unwrap();
                        session.import_rsa_wrapped_key(
                            wrap_op_spec.wrapkey_id,
                            key_spec.object_type,
                            key_spec.id,
                            key_spec.algorithm,
                            &key_spec.label,
                            &key_spec.domains,
                            &key_spec.capabilities,
                            oaep_algo,
                            mgf1_algo,
                            &oaep_label,
                            &data,
                        )?
                    }
                }
            }
            WrapKeyType::RsaPublic => {
                return Err(MgmError::InvalidInput("Public RSA key cannot be used for unwrapped".to_string()))
            }
        };

        Ok(handle)
    }

    /// Parse a yubihsm-setup / rusty_secrets 0.0.2 share string of the form
    /// "{k}-{share_id}-{base64(raw_shamir_bytes)}" and return a Vec<u8> in the
    /// format that gf256::shamir::reconstruct expects:
    ///   [ share_id, y_byte_0, y_byte_1, ... ]
    fn rusty_share_to_gf256_share(share_str: &str) -> Vec<u8> {
        let parts: Vec<&str> = share_str.trim().splitn(3, '-').collect();
        assert_eq!(parts.len(), 3, "Expected format k-id-base64data");

        let share_id: u8 = parts[1].parse().expect("Invalid share id");

        // In rusty_secrets 0.0.2, the third part is simply base64(raw_shamir_bytes).
        // No protobuf wrapping — that was added in later versions.
        let shamir_data = STANDARD_NO_PAD.decode(parts[2]).expect("Base64 decode failed");

        // Build the gf256 share: [x_coordinate=share_id, y_bytes...]
        let mut gf256_share = Vec::with_capacity(1 + shamir_data.len());
        gf256_share.push(share_id);
        gf256_share.extend_from_slice(&shamir_data);
        gf256_share
    }

    fn get_oaep_label(algorithm: &ObjectAlgorithm) -> Result<Vec<u8>, MgmError> {
        let oaep_label: &[u8] = &[];
        AsymmetricOperations::get_hashed_bytes(algorithm, oaep_label)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── Helper: build a NewObjectSpec that looks like a wrap key ──
    fn make_wrapkey_spec(algo: ObjectAlgorithm, key_bytes: Vec<u8>) -> NewObjectSpec {
        NewObjectSpec {
            id: 0x0010,
            object_type: ObjectType::WrapKey,
            label: "test-wrap".to_string(),
            algorithm: algo,
            domains: vec![ObjectDomain::One],
            capabilities: vec![ObjectCapability::ExportWrapped],
            delegated_capabilities: vec![ObjectCapability::ExportableUnderWrap],
            data: vec![key_bytes],
        }
    }

    // ══════════════════════════════════════════════
    //  get_unwrapped_key_algorithms
    // ══════════════════════════════════════════════

    #[test]
    fn test_unwrapped_key_algorithms_non_empty() {
        let algos = WrapOperations::get_rsa_unwrapped_key_algorithms();
        let expected_len =
            MgmAlgorithm::RSA_KEY_ALGORITHMS.len() +
            MgmAlgorithm::EC_KEY_ALGORITHMS.len() +
            MgmAlgorithm::ED_KEY_ALGORITHMS.len() +
            MgmAlgorithm::AES_KEY_ALGORITHMS.len();
        assert_eq!(algos.len(), expected_len);
        assert!(algos.iter().all(|algo|
            MgmAlgorithm::RSA_KEY_ALGORITHMS.contains(algo) ||
            MgmAlgorithm::EC_KEY_ALGORITHMS.contains(algo) ||
            MgmAlgorithm::ED_KEY_ALGORITHMS.contains(algo) ||
            MgmAlgorithm::AES_KEY_ALGORITHMS.contains(algo)));
    }

    // ══════════════════════════════════════════════
    //  split_wrap_key + get_wrapkey_from_shares round-trip
    // ══════════════════════════════════════════════

    #[test]
    fn test_split_produces_correct_share_count() {
        let key = vec![0xABu8; 16]; // 128-bit key
        let spec = make_wrapkey_spec(ObjectAlgorithm::Aes128CcmWrap, key);
        let result = WrapOperations::split_wrap_key(&spec, 2, 3).unwrap();
        assert_eq!(result.shares, 3);
        assert_eq!(result.threshold, 2);
        assert_eq!(result.shares_data.len(), 3);
    }

    #[test]
    fn test_split_roundtrip_aes128() {
        let key = vec![0x42u8; 16];
        let spec = make_wrapkey_spec(ObjectAlgorithm::Aes128CcmWrap, key.clone());
        let split = WrapOperations::split_wrap_key(&spec, 2, 3).unwrap();

        // Reconstruct from any 2 of the 3 shares
        let subset = vec![split.shares_data[0].clone(), split.shares_data[1].clone()];
        let recovered = WrapOperations::get_wrapkey_from_shares(subset).unwrap();

        assert_eq!(recovered.id, spec.id);
        assert_eq!(recovered.object_type, spec.object_type);
        assert_eq!(recovered.label, ""); // Label is not included in the split data
        assert_eq!(recovered.algorithm, spec.algorithm);
        assert_eq!(recovered.domains, spec.domains);
        assert_eq!(recovered.capabilities, spec.capabilities);
        assert_eq!(recovered.delegated_capabilities, spec.delegated_capabilities);
        assert_eq!(recovered.data[0], key);
    }

    #[test]
    fn test_split_roundtrip_aes192() {
        let key = vec![0x47u8; 24];
        let spec = make_wrapkey_spec(ObjectAlgorithm::Aes192, key.clone());
        let split = WrapOperations::split_wrap_key(&spec, 3, 3).unwrap();
        assert_eq!(split.shares_data.len(), 3);

        let subset = vec![
            split.shares_data[0].clone(),
            split.shares_data[1].clone(),
            split.shares_data[2].clone(),
        ];
        let recovered = WrapOperations::get_wrapkey_from_shares(subset).unwrap();
        assert_eq!(recovered.data[0], key);
    }

    #[test]
    fn test_split_roundtrip_aes256() {
        let key = vec![0x99u8; 32];
        let spec = make_wrapkey_spec(ObjectAlgorithm::Aes256CcmWrap, key.clone());
        let split = WrapOperations::split_wrap_key(&spec, 3, 5).unwrap();
        assert_eq!(split.shares_data.len(), 5);

        let subset = vec![
            split.shares_data[0].clone(),
            split.shares_data[2].clone(),
            split.shares_data[4].clone(),
        ];
        let recovered = WrapOperations::get_wrapkey_from_shares(subset).unwrap();
        assert_eq!(recovered.data[0], key);
    }

    // ══════════════════════════════════════════════
    //  New-style (vsss-rs hex) shares — known key values
    // ══════════════════════════════════════════════

    // Secret: a6c42207000000000000300000000000010331f0e0a131a9f6c571e64fce024930f6c3abff0728bedb4e356cbbbf92c3337accf4
    // Key: e0a131a9f6c571e64fce024930f6c3abff0728bedb4e356cbbbf92c3337accf4
    // ID: 0x9872
    // Domains: 1,2,3,10,14.
    // Capabilities: export-wrapped,import-wrapped.
    // Delegated capabilities: generate-asymmetric-key,sign-pkcs,sign-pss,sign-ecdsa,sign-eddsa,export-wrapped,import-wrapped,exportable-under-wrap,set-option,get-log-entries
    // Format: 3-of-5, AES-256, produced by yubihsm-manager
    const NEW_STYLE_AES256_KEY: &str =
        "e0a131a9f6c571e64fce024930f6c3abff0728bedb4e356cbbbf92c3337accf4";
    const NEW_STYLE_AES256_SHARES: [&str; 5] = [
        "3-1-2ce8ca8b4cb67ed4b85404b8ce58086255936f22bc0f2185e0d9339639e27083e62e4925f3759c48c34e5bd0eb114225d7e48a76",
        "3-2-0f175c8137a54b27916021de1f8d1f1a2044d063ddcd854f986b8bda60f58969d49cb26a3e06823b8657ed7adde644dcc2244d71",
        "3-3-853bb40d7b1335f329341566d1d5177874d48eb1816395638e77c9aa16d9fba3024438e4327436cd9e5783c68d48943a26ba0bf3",
        "3-4-41633c32e4347c28fccded4568f502615166877db8d524b039ec7dc3302fa883b40bc2072fbc2e7cce188e8f42758af04239e1bb",
        "3-5-cb4fd4bea88202fc4499d9fda6ad0a0305f6d9afe47b349c2ff03fb34603da4962d3488923ce9a8ad618e03312db5a16a6a7a739",
    ];

    #[test]
    fn test_new_style_aes256_key_value_minimum_threshold() {
        let expected = hex::decode(NEW_STYLE_AES256_KEY).unwrap();
        let shares = vec![
            NEW_STYLE_AES256_SHARES[0].to_string(),
            NEW_STYLE_AES256_SHARES[1].to_string(),
            NEW_STYLE_AES256_SHARES[2].to_string(),
        ];
        let recovered = WrapOperations::get_wrapkey_from_shares(shares).unwrap();
        assert_eq!(recovered.data[0], expected);
        assert_eq!(recovered.algorithm, ObjectAlgorithm::Aes256CcmWrap);
        assert_eq!(recovered.object_type, ObjectType::WrapKey);
        assert_eq!(recovered.id, 0xa6c4);
        assert_eq!(recovered.domains, vec![ObjectDomain::One, ObjectDomain::Two, ObjectDomain::Three, ObjectDomain::Ten, ObjectDomain::Fourteen]);
        assert_eq!(recovered.capabilities, vec![ObjectCapability::ExportWrapped, ObjectCapability::ImportWrapped]);
        assert_eq!(recovered.delegated_capabilities, vec![
            ObjectCapability::GenerateAsymmetricKey,
            ObjectCapability::SignPkcs,
            ObjectCapability::SignPss,
            ObjectCapability::SignEcdsa,
            ObjectCapability::SignEddsa,
            ObjectCapability::ExportWrapped,
            ObjectCapability::ImportWrapped,
            ObjectCapability::ExportableUnderWrap,
            ObjectCapability::SetOption,
            ObjectCapability::GetLogEntries,
        ]);
    }

    #[test]
    fn test_new_style_aes256_all_combinations_of_threshold() {
        let expected = hex::decode(NEW_STYLE_AES256_KEY).unwrap();
        // Verify any 3-of-5 combination produces the same key
        let indices = [(0,1,2), (0,1,3), (0,1,4), (0,2,3), (0,2,4),
            (0,3,4), (1,2,3), (1,2,4), (1,3,4), (2,3,4)];
        for (i, j, k) in indices {
            let shares = vec![
                NEW_STYLE_AES256_SHARES[i].to_string(),
                NEW_STYLE_AES256_SHARES[j].to_string(),
                NEW_STYLE_AES256_SHARES[k].to_string(),
            ];
            let recovered = WrapOperations::get_wrapkey_from_shares(shares).unwrap();
            assert_eq!(recovered.data[0], expected,
                       "Key mismatch for share combination ({}, {}, {})", i+1, j+1, k+1);
            assert_eq!(recovered.algorithm, ObjectAlgorithm::Aes256CcmWrap,
                       "Key mismatch for share combination ({}, {}, {})", i+1, j+1, k+1);
            assert_eq!(recovered.object_type, ObjectType::WrapKey,
                       "Key mismatch for share combination ({}, {}, {})", i+1, j+1, k+1);
            assert_eq!(recovered.id, 0xa6c4, "Key mismatch for share combination ({}, {}, {})", i+1, j+1, k+1);
            assert_eq!(recovered.domains, vec![ObjectDomain::One, ObjectDomain::Two, ObjectDomain::Three, ObjectDomain::Ten, ObjectDomain::Fourteen],
                       "Key mismatch for share combination ({}, {}, {})", i+1, j+1, k+1);
            assert_eq!(recovered.capabilities, vec![ObjectCapability::ExportWrapped, ObjectCapability::ImportWrapped],
                       "Key mismatch for share combination ({}, {}, {})", i+1, j+1, k+1);
            assert_eq!(recovered.delegated_capabilities, vec![
                ObjectCapability::GenerateAsymmetricKey,
                ObjectCapability::SignPkcs,
                ObjectCapability::SignPss,
                ObjectCapability::SignEcdsa,
                ObjectCapability::SignEddsa,
                ObjectCapability::ExportWrapped,
                ObjectCapability::ImportWrapped,
                ObjectCapability::ExportableUnderWrap,
                ObjectCapability::SetOption,
                ObjectCapability::GetLogEntries,
            ], "Key mismatch for share combination ({}, {}, {})", i+1, j+1, k+1);
        }
    }

    // Secret: 56cc01dd000000000000300000000000010539f04aefbda19e97f58dbbca200621ac6c2c
    // Key: 4aefbda19e97f58dbbca200621ac6c2c
    // ID: 0x56cc
    // Domains: 1,3,4,5,7,8,9
    // Capabilities: export-wrapped,import-wrapped.
    // Delegated capabilities: generate-asymmetric-key,sign-pkcs,sign-ecdsa,sign-eddsa,derive-ecdh,export-wrapped,import-wrapped,exportable-under-wrap,set-option,get-log-entries
    // Format: 2-of-3, AES-128, produced by yubihsm-manager
    const NEW_STYLE_AES128_KEY: &str = "4aefbda19e97f58dbbca200621ac6c2c";
    const NEW_STYLE_AES128_SHARES: [&str; 3] = [
        "2-1-f734da8c8b914be5a96533a18961a13b6266260717322e5659acf6aede5767a5e00ded39",
        "2-2-4d18ac7f0d3996d149ca365909c25976c7c907c5f04e80540be1f3cb71ebae5bb8f57506",
        "2-3-d2f5772e86a8dd34e0af35f880a3f84da4ac1872ad9313a3ccdaf0e81476e9f87954f413",
    ];

    #[test]
    fn test_new_style_aes128_key_value_minimum_threshold() {
        let expected = hex::decode(NEW_STYLE_AES128_KEY).unwrap();
        let shares = vec![
            NEW_STYLE_AES128_SHARES[0].to_string(),
            NEW_STYLE_AES128_SHARES[1].to_string(),
        ];
        let recovered = WrapOperations::get_wrapkey_from_shares(shares).unwrap();
        assert_eq!(recovered.data[0], expected);
        assert_eq!(recovered.algorithm, ObjectAlgorithm::Aes128CcmWrap);
        assert_eq!(recovered.object_type, ObjectType::WrapKey);
        assert_eq!(recovered.id, 0x68d9);
        assert_eq!(recovered.domains, vec![ObjectDomain::One, ObjectDomain::Three, ObjectDomain::Four, ObjectDomain::Five, ObjectDomain::Seven, ObjectDomain::Eight, ObjectDomain::Nine]);
        assert_eq!(recovered.capabilities, vec![ObjectCapability::ExportWrapped, ObjectCapability::ImportWrapped]);
        assert_eq!(recovered.delegated_capabilities, vec![
            ObjectCapability::GenerateAsymmetricKey,
            ObjectCapability::SignPkcs,
            ObjectCapability::SignEcdsa,
            ObjectCapability::SignEddsa,
            ObjectCapability::DeriveEcdh,
            ObjectCapability::ExportWrapped,
            ObjectCapability::ImportWrapped,
            ObjectCapability::ExportableUnderWrap,
            ObjectCapability::SetOption,
            ObjectCapability::GetLogEntries,
        ]);
    }

    #[test]
    fn test_new_style_aes128_all_combinations_of_threshold() {
        let expected = hex::decode(NEW_STYLE_AES128_KEY).unwrap();
        for (i, j) in [(0,1), (0,2), (1,2)] {
            let shares = vec![
                NEW_STYLE_AES128_SHARES[i].to_string(),
                NEW_STYLE_AES128_SHARES[j].to_string(),
            ];
            let recovered = WrapOperations::get_wrapkey_from_shares(shares).unwrap();
            assert_eq!(recovered.data[0], expected,
                       "Key mismatch for share combination ({}, {})", i+1, j+1);
            assert_eq!(recovered.algorithm, ObjectAlgorithm::Aes128CcmWrap,
                       "Key mismatch for share combination ({}, {})", i+1, j+1);
            assert_eq!(recovered.object_type, ObjectType::WrapKey,
                       "Key mismatch for share combination ({}, {})", i+1, j+1);
            assert_eq!(recovered.id, 0x68d9, "Key mismatch for share combination ({}, {})", i+1, j+1);
            assert_eq!(recovered.domains, vec![ObjectDomain::One, ObjectDomain::Three, ObjectDomain::Four, ObjectDomain::Five, ObjectDomain::Seven, ObjectDomain::Eight, ObjectDomain::Nine],
                       "Key mismatch for share combination ({}, {})", i+1, j+1);
            assert_eq!(recovered.capabilities, vec![ObjectCapability::ExportWrapped, ObjectCapability::ImportWrapped],
                       "Key mismatch for share combination ({}, {})", i+1, j+1);
            assert_eq!(recovered.delegated_capabilities, vec![
                ObjectCapability::GenerateAsymmetricKey,
                ObjectCapability::SignPkcs,
                ObjectCapability::SignEcdsa,
                ObjectCapability::SignEddsa,
                ObjectCapability::DeriveEcdh,
                ObjectCapability::ExportWrapped,
                ObjectCapability::ImportWrapped,
                ObjectCapability::ExportableUnderWrap,
                ObjectCapability::SetOption,
                ObjectCapability::GetLogEntries,
            ], "Key mismatch for share combination ({}, {})", i+1, j+1);
        }
    }

    #[test]
    fn test_new_style_aes128_all_shares_returns_correct_key() {
        let expected = hex::decode(NEW_STYLE_AES128_KEY).unwrap();
        let shares = NEW_STYLE_AES128_SHARES.iter().map(|s| s.to_string()).collect();
        let recovered = WrapOperations::get_wrapkey_from_shares(shares).unwrap();
        assert_eq!(recovered.data[0], expected);
    }

    // ══════════════════════════════════════════════
    //  Legacy (yubihsm-setup base64) shares — known key values
    // ══════════════════════════════════════════════

    // Secret: 98722207000000000000300000000000010539f0e0a131a9f6c571e64fce024930f6c3abff0728bedb4e356cbbbf92c3337accf4
    // Key: e0a131a9f6c571e64fce024930f6c3abff0728bedb4e356cbbbf92c3337accf4
    // ID: 0x9872
    // Domains: 1,2,3,10,14.
    // Capabilities: export-wrapped,import-wrapped.
    // Delegated capabilities: generate-asymmetric-key,sign-pkcs,sign-pss,sign-ecdsa,sign-eddsa,derive-ecdh,export-wrapped,import-wrapped,exportable-under-wrap,get-option,get-log-entries
    // Format: 3-of-5, AES-256, produced by yubihsm-setup
    const LEGACY_AES256_KEY: &str =
        "e0a131a9f6c571e64fce024930f6c3abff0728bedb4e356cbbbf92c3337accf4";
    const LEGACY_AES256_SHARES: [&str; 5] = [
        "3-1-NOJmWrDY3dxtzpwDnukPvFL/joSlG8xbr75OxCZ4OEVcaOSYVBD4uTfEZIzR0vKNmQm0Bw",
        "3-2-MEApAYsY0KaD8h1WAoo2ak+qDXoqgPCdTibn9z/f9nHduaXpet+vu00942mEMvgHEE92ew",
        "3-3-nNBtXDvADXruPLFVnGM51hxQug5vOg1vF13Y1VZpzH2xJ4La0ch/vKG3sonuX5hJujwOiA",
        "3-4-RioCwfTefF1iKNfxiADM6BpDUGx03jbSs0rHjR1xzbkjza+/91XTmLtdSSFO+dQrwHuQOg",
        "3-5-6rpGnEQGoYEP5nvyFunDVEm55xgxZMsg6jH4r3TH97VPU4iMXEIDn1fXGMEklLRlagjoyQ",
    ];

    #[test]
    fn test_legacy_aes256_key_value_minimum_threshold() {
        let expected = hex::decode(LEGACY_AES256_KEY).unwrap();
        let shares = vec![
            LEGACY_AES256_SHARES[0].to_string(),
            LEGACY_AES256_SHARES[1].to_string(),
            LEGACY_AES256_SHARES[2].to_string(),
        ];
        let recovered = WrapOperations::get_wrapkey_from_shares(shares).unwrap();
        assert_eq!(recovered.data[0], expected);
        assert_eq!(recovered.algorithm, ObjectAlgorithm::Aes256CcmWrap);
        assert_eq!(recovered.object_type, ObjectType::WrapKey);
        assert_eq!(recovered.id, 0x9872);
        assert_eq!(recovered.domains, vec![ObjectDomain::One, ObjectDomain::Two, ObjectDomain::Three, ObjectDomain::Ten, ObjectDomain::Fourteen]);
        assert_eq!(recovered.capabilities, vec![ObjectCapability::ExportWrapped, ObjectCapability::ImportWrapped]);
        assert_eq!(recovered.delegated_capabilities, vec![
            ObjectCapability::GenerateAsymmetricKey,
            ObjectCapability::SignPkcs,
            ObjectCapability::SignPss,
            ObjectCapability::SignEcdsa,
            ObjectCapability::SignEddsa,
            ObjectCapability::DeriveEcdh,
            ObjectCapability::ExportWrapped,
            ObjectCapability::ImportWrapped,
            ObjectCapability::ExportableUnderWrap,
            ObjectCapability::GetOption,
            ObjectCapability::GetLogEntries,
        ]);
    }

    #[test]
    fn test_legacy_aes256_all_combinations_of_threshold() {
        let expected = hex::decode(LEGACY_AES256_KEY).unwrap();
        let indices = [(0,1,2), (0,1,3), (0,1,4), (0,2,3), (0,2,4),
            (0,3,4), (1,2,3), (1,2,4), (1,3,4), (2,3,4)];
        for (i, j, k) in indices {
            let shares = vec![
                LEGACY_AES256_SHARES[i].to_string(),
                LEGACY_AES256_SHARES[j].to_string(),
                LEGACY_AES256_SHARES[k].to_string(),
            ];
            let recovered = WrapOperations::get_wrapkey_from_shares(shares).unwrap();
            assert_eq!(recovered.data[0], expected,
                       "Key mismatch for share combination ({}, {}, {})", i+1, j+1, k+1);
            assert_eq!(recovered.algorithm, ObjectAlgorithm::Aes256CcmWrap,
                       "Key mismatch for share combination ({}, {}, {})", i+1, j+1, k+1);
            assert_eq!(recovered.object_type, ObjectType::WrapKey,
                       "Key mismatch for share combination ({}, {}, {})", i+1, j+1, k+1);
            assert_eq!(recovered.id, 0x9872, "Key mismatch for share combination ({}, {}, {})", i+1, j+1, k+1);
            assert_eq!(recovered.domains, vec![ObjectDomain::One, ObjectDomain::Two, ObjectDomain::Three, ObjectDomain::Ten, ObjectDomain::Fourteen],
                       "Key mismatch for share combination ({}, {}, {})", i+1, j+1, k+1);
            assert_eq!(recovered.capabilities, vec![ObjectCapability::ExportWrapped, ObjectCapability::ImportWrapped],
                       "Key mismatch for share combination ({}, {}, {})", i+1, j+1, k+1);
            assert_eq!(recovered.delegated_capabilities, vec![
                ObjectCapability::GenerateAsymmetricKey,
                ObjectCapability::SignPkcs,
                ObjectCapability::SignPss,
                ObjectCapability::SignEcdsa,
                ObjectCapability::SignEddsa,
                ObjectCapability::DeriveEcdh,
                ObjectCapability::ExportWrapped,
                ObjectCapability::ImportWrapped,
                ObjectCapability::ExportableUnderWrap,
                ObjectCapability::GetOption,
                ObjectCapability::GetLogEntries,
            ], "Key mismatch for share combination ({}, {}, {})", i+1, j+1, k+1);
        }
    }

    #[test]
    fn test_legacy_aes256_all_five_shares_returns_correct_key() {
        let expected = hex::decode(LEGACY_AES256_KEY).unwrap();
        let shares = LEGACY_AES256_SHARES.iter().map(|s| s.to_string()).collect();
        let recovered = WrapOperations::get_wrapkey_from_shares(shares).unwrap();
        assert_eq!(recovered.data[0], expected);
    }

    // Secret: 56cc01dd000000000000300000000000010539f04aefbda19e97f58dbbca200621ac6c2c
    // Key: 4aefbda19e97f58dbbca200621ac6c2c
    // ID: 0x56cc
    // Domains: 1,3,4,5,7,8,9
    // Capabilities: export-wrapped,import-wrapped.
    // Delegated capabilities: generate-asymmetric-key,sign-pkcs,sign-pss,sign-ecdsa,sign-eddsa,derive-ecdh,export-wrapped,import-wrapped,exportable-under-wrap,get-option,get-log-entries
    // Format: 2-of-3, AES-128, produced by yubihsm-setup
    const LEGACY_AES128_KEY: &str = "4aefbda19e97f58dbbca200621ac6c2c";
    const LEGACY_AES128_SHARES: [&str; 3] = [
        "2-1-iwD5Pz8GVdO/ADSxP3x30zMGpsb5hxIcGE3xDfU8aZC2lMNR",
        "2-2-8UnsBH4MqrtjADh/fvjuu2UDGpwxP/7Gjz79kCc7sjcS3C/W",
        "2-3-LIUU5kEK/2jcADzOQYSZaFcAhaqCV1F7CeT5EGnN+6GF5ICr",
    ];

    #[test]
    fn test_legacy_aes128_key_value_minimum_threshold() {
        let expected = hex::decode(LEGACY_AES128_KEY).unwrap();
        let shares = vec![
            LEGACY_AES128_SHARES[0].to_string(),
            LEGACY_AES128_SHARES[1].to_string(),
        ];
        let recovered = WrapOperations::get_wrapkey_from_shares(shares).unwrap();
        assert_eq!(recovered.data[0], expected);
        assert_eq!(recovered.algorithm, ObjectAlgorithm::Aes128CcmWrap);
        assert_eq!(recovered.object_type, ObjectType::WrapKey);
        assert_eq!(recovered.id, 0x56cc);
        assert_eq!(recovered.domains, vec![ObjectDomain::One, ObjectDomain::Three, ObjectDomain::Four, ObjectDomain::Five, ObjectDomain::Seven, ObjectDomain::Eight, ObjectDomain::Nine]);
        assert_eq!(recovered.capabilities, vec![ObjectCapability::ExportWrapped, ObjectCapability::ImportWrapped]);
        assert_eq!(recovered.delegated_capabilities, vec![
            ObjectCapability::GenerateAsymmetricKey,
            ObjectCapability::SignPkcs,
            ObjectCapability::SignPss,
            ObjectCapability::SignEcdsa,
            ObjectCapability::SignEddsa,
            ObjectCapability::DeriveEcdh,
            ObjectCapability::ExportWrapped,
            ObjectCapability::ImportWrapped,
            ObjectCapability::ExportableUnderWrap,
            ObjectCapability::GetOption,
            ObjectCapability::GetLogEntries,
        ]);
    }

    #[test]
    fn test_legacy_aes128_all_combinations_of_threshold() {
        let expected = hex::decode(LEGACY_AES128_KEY).unwrap();
        for (i, j) in [(0,1), (0,2), (1,2)] {
            let shares = vec![
                LEGACY_AES128_SHARES[i].to_string(),
                LEGACY_AES128_SHARES[j].to_string(),
            ];
            let recovered = WrapOperations::get_wrapkey_from_shares(shares).unwrap();
            assert_eq!(recovered.data[0], expected,
                       "Key mismatch for share combination ({}, {})", i+1, j+1);
            assert_eq!(recovered.algorithm, ObjectAlgorithm::Aes128CcmWrap,
                       "Key mismatch for share combination ({}, {})", i+1, j+1);
            assert_eq!(recovered.object_type, ObjectType::WrapKey,
                       "Key mismatch for share combination ({}, {})", i+1, j+1);
            assert_eq!(recovered.id, 0x56cc, "Key mismatch for share combination ({}, {})", i+1, j+1);
            assert_eq!(recovered.domains, vec![ObjectDomain::One, ObjectDomain::Three, ObjectDomain::Four, ObjectDomain::Five, ObjectDomain::Seven, ObjectDomain::Eight, ObjectDomain::Nine],
                       "Key mismatch for share combination ({}, {})", i+1, j+1);
            assert_eq!(recovered.capabilities, vec![ObjectCapability::ExportWrapped, ObjectCapability::ImportWrapped],
                       "Key mismatch for share combination ({}, {})", i+1, j+1);
            assert_eq!(recovered.delegated_capabilities, vec![
                ObjectCapability::GenerateAsymmetricKey,
                ObjectCapability::SignPkcs,
                ObjectCapability::SignPss,
                ObjectCapability::SignEcdsa,
                ObjectCapability::SignEddsa,
                ObjectCapability::DeriveEcdh,
                ObjectCapability::ExportWrapped,
                ObjectCapability::ImportWrapped,
                ObjectCapability::ExportableUnderWrap,
                ObjectCapability::GetOption,
                ObjectCapability::GetLogEntries,
            ], "Key mismatch for share combination ({}, {})", i+1, j+1);
        }
    }

    #[test]
    fn test_legacy_aes128_all_shares_returns_correct_key() {
        let expected = hex::decode(LEGACY_AES128_KEY).unwrap();
        let shares = LEGACY_AES128_SHARES.iter().map(|s| s.to_string()).collect();
        let recovered = WrapOperations::get_wrapkey_from_shares(shares).unwrap();
        assert_eq!(recovered.data[0], expected);
    }

    // ══════════════════════════════════════════════
    //  Format auto-detection
    // ══════════════════════════════════════════════

    // Verify that the two formats for the same key return the exact same result
    #[test]
    fn test_legacy_and_new_style_aes256_produce_identical_specs() {
        let legacy_shares = vec![
            LEGACY_AES256_SHARES[0].to_string(),
            LEGACY_AES256_SHARES[1].to_string(),
            LEGACY_AES256_SHARES[2].to_string(),
        ];
        let new_shares = vec![
            NEW_STYLE_AES256_SHARES[0].to_string(),
            NEW_STYLE_AES256_SHARES[1].to_string(),
            NEW_STYLE_AES256_SHARES[2].to_string(),
        ];
        let legacy_recovered = WrapOperations::get_wrapkey_from_shares(legacy_shares).unwrap();
        let new_recovered = WrapOperations::get_wrapkey_from_shares(new_shares).unwrap();

        assert_eq!(legacy_recovered.data[0], new_recovered.data[0]);
        assert_eq!(legacy_recovered.algorithm, new_recovered.algorithm);
    }

    #[test]
    fn test_legacy_and_new_style_aes128_produce_identical_specs() {
        let legacy_shares = vec![
            LEGACY_AES128_SHARES[0].to_string(),
            LEGACY_AES128_SHARES[1].to_string(),
        ];
        let new_shares = vec![
            NEW_STYLE_AES128_SHARES[0].to_string(),
            NEW_STYLE_AES128_SHARES[1].to_string(),
        ];
        let legacy_recovered = WrapOperations::get_wrapkey_from_shares(legacy_shares).unwrap();
        let new_recovered = WrapOperations::get_wrapkey_from_shares(new_shares).unwrap();

        assert_eq!(legacy_recovered.data[0], new_recovered.data[0]);
        assert_eq!(legacy_recovered.algorithm, new_recovered.algorithm);
    }

    // ══════════════════════════════════════════════
    //  Error cases
    // ══════════════════════════════════════════════

    #[test]
    fn test_new_style_invalid_hex_data_returns_error() {
        // Corrupt the hex payload of an otherwise valid share
        let shares = vec![
            "2-1-zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz".to_string(),
            "2-2-4d18ac7f0d3996d149ca365909c25976c7c907c5f04e80540be1f3cb71ebae5bb8f57506".to_string(),
        ];
        // First share hex is invalid, but the detection uses shares[0]'s last part.
        // The z's are not valid hex, so it will be routed to legacy path and base64-decoded.
        // It may succeed or fail depending on padding — we just verify it doesn't panic
        // and that it doesn't produce the correct key.
        let expected = hex::decode(NEW_STYLE_AES128_KEY).unwrap();
        let result = WrapOperations::get_wrapkey_from_shares(shares);
        if let Ok(recovered) = result {
            assert_ne!(recovered.data[0], expected, "Corrupted share should not yield correct key");
        }
        // If it errors, that's also correct behaviour
    }

    #[test]
    fn test_new_style_aes256_insufficient_shares_returns_wrong_key() {
        // Providing only 2 shares when threshold is 3 should succeed structurally
        // but return a garbage key (Shamir property: fewer than threshold shares
        // yield an arbitrary value, not an error)
        let shares = vec![
            NEW_STYLE_AES256_SHARES[0].to_string(),
            NEW_STYLE_AES256_SHARES[1].to_string(),
        ];
        let result = WrapOperations::get_wrapkey_from_shares(shares);
        assert!(result.is_err(), "Providing fewer than threshold shares should return an error");
    }

    #[test]
    fn test_legacy_aes256_insufficient_shares_returns_wrong_key() {
        let shares = vec![
            LEGACY_AES256_SHARES[0].to_string(),
            LEGACY_AES256_SHARES[1].to_string(),
        ];
        let result = WrapOperations::get_wrapkey_from_shares(shares);
        assert!(result.is_err(), "Providing fewer than threshold shares should return an error");
    }
}