[licenses]
confidence-threshold = 0.8
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  #"ISC",
  "Unicode-3.0",
  #"Unicode-DFS-2016",
  "MPL-2.0",
  "Zlib",
]

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "warn"
unknown-git = "allow"
allow-git = [
  "https://github.com/Yubico/yubihsmrs.git",
]
