== YubiHSM Manager

Command line tool for YubiHSM 2. This is a work in progress and is currently not supported and not part of the official YubiHSM SDK

YubiHSM Manger is mainly used to manage asymmetric and symmetric keys, authentication keys and wrap keys as well as
setting up the YubiHSM2 for specific usecases.

Use this tool instead of yubihsm-setup. Use Space key to select and deselect options in multi-choice questions. Use ESC
key to cancel current operation.

=== Build

To build the tool a normal Rust toolchain is required, stable Rust will suffice.

The tools uses the `yubihsmrs` crate as obtained from https://github.com/Yubico/yubihsmrs/tree/yubihsm-manager (note
the `yubihsm-manager` branch), which in turn requires `libyubihsm` to be available.

Set the environment variable `YUBIHSM_LIB_DIR` to point to the directory containing the libyubihsm library then run:

```
$ cargo build
```

==== Note about building

Currently `yubihsmrs` has not been published to crates.io. This means that either a local or a git path should be
specified when adding it as dependency. Specifically, `yubihsm-manager` expects to find `yubihsmrs` inside `../yubihsmrs/`.

=== Run

Set the environment variable `LD_LIBRARY_PATH` to point to the directory containing the libyubihsm library then run:

```
$ cargo run
```

Or

```
$ ./target/debug/yubihsm-manager
```

Note that on Windows, the libyubihsm.dll need to be in PATH

== License

....
 Copyright 2025 Yubico AB

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
....