/*
 * Copyright 2025 Yubico AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

use yubihsmrs::object::{ObjectCapability, ObjectDescriptor};
use yubihsmrs::Session;
use crate::backend::common::get_authorized_commands;
use crate::backend::error::MgmError;
use crate::backend::types::{CommandSpec, YhCommand};

pub struct DeviceOps;

impl DeviceOps {

    const DEVICE_COMMANDS: [CommandSpec;6] = [
        CommandSpec {
            command: YhCommand::GetRandom,
            label: "Generate pseudo random number",
            description: "Get pseudo random bytes generated by the YubiHSM",
            required_capabilities: &[ObjectCapability::GetPseudoRandom],
            require_all_capabilities: false,
        },
        CommandSpec {
            command: YhCommand::BackupDevice,
            label: "Backup device",
            description: "Exports all exportable objects under wrap",
            required_capabilities: &[ObjectCapability::ExportWrapped],
            require_all_capabilities: false,
        },
        CommandSpec {
            command: YhCommand::RestoreDevice,
            label: "Restore device",
            description: "Reads all files ending with .yhw in a specified directory and imports the wrapped objects",
            required_capabilities: &[ObjectCapability::ImportWrapped],
            require_all_capabilities: false,
        },
        CommandSpec {
            command: YhCommand::Reset,
            label: "Reset device",
            description: "Restores the YubiHSM to factory default settings. All data will be deleted from the device and cannot be recovered",
            required_capabilities: &[],
            require_all_capabilities: false,
        },
        CommandSpec::RETURN_COMMAND,
        CommandSpec::EXIT_COMMAND,
    ];

    pub fn get_authorized_commands(
        authkey: &ObjectDescriptor,
    ) -> Vec<CommandSpec> {
        get_authorized_commands(authkey, &Self::DEVICE_COMMANDS)
    }

    pub fn get_random(session: &Session, num_bytes: usize) -> Result<Vec<u8>, MgmError> {
        Ok(session.get_random(num_bytes)?)
    }

    pub fn reset_device(session: &Session) -> Result<(), MgmError> {
        Ok(session.reset()?)
    }

}