name: "Building binaries for Linux, MacOS and Windows"

on: [push]

jobs:

  Ubuntu-Build:
    name: Ubuntu
    runs-on: ubuntu-latest
    env:
      YUBIHSMSDK_VERSION: 2023-08

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # download yubihsm-sdk installer from dev.y.c and install it
      - name: install yubihsm-shell
        run: |
          set -e -o pipefail
          set -x

          cd ..
          curl -L --max-redirs 2 -o - https://developers.yubico.com/YubiHSM2/Releases/yubihsm2-sdk-$YUBIHSMSDK_VERSION-ubuntu2204-amd64.tar.gz |\
              tar -xzvf -
          cd yubihsm2-sdk
          sudo dpkg -i ./libyubihsm*_amd64.deb

      - name: clone yubihsmrs
        run: |
          set -e -o pipefail
          set -x

          cd ..
          git clone -b yubihsm-manager https://github.com/Yubico/yubihsmrs.git

      - name: Build yubihsm-manager
        run: |
          set -e -o pipefail
          set -x
          mkdir -p artifact/yubihsm-manager

          cd ..
          export PATH=$PATH:~/.cargo/bin
          if [[ ! -x $(command -v rustc) ]]; then
            curl -o rustup.sh https://sh.rustup.rs
            bash ./rustup.sh -y
          fi
          cargo install cargo-deb

          cd yubihsm-manager
          YUBIHSM_LIB_DIR=$(dpkg -L libyubihsm1 | grep -e "libyubihsm.so.2$" | xargs dirname) cargo build --release
          strip --strip-all target/release/yubihsm-manager
          cargo deb --no-build
          cp target/debian/*.deb artifact/yubihsm-manager/

          ./target/release/yubihsm-manager --version
          ./target/release/yubihsm-manager --help

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: yubihsm-manager-deb
          path: artifact

  MacOS-Build:
    name: MacOS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            arch: amd
          - os: macos-latest-xlarge
            arch: arm
    env:
      YUBIHSMSDK_VERSION: 2023-08

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # download yubihsm-sdk installer from dev.y.c and install it
      - name: install yubihsm-shell
        run: |
          set -e -o pipefail
          set -x

          cd ..
          curl -L --max-redirs 2 -o yubihsm-sdk-installer.pkg https://developers.yubico.com/YubiHSM2/Releases/yubihsm2-sdk-$YUBIHSMSDK_VERSION-darwin-universal.pkg
          sudo installer -verbose -store -pkg yubihsm-sdk-installer.pkg -target /

      - name: clone yubihsmrs
        run: |
          set -e -o pipefail
          set -x

          cd ..
          git clone -b yubihsm-manager https://github.com/Yubico/yubihsmrs.git

      - name: Build yubihsm-manager
        run: |
          set -e -o pipefail
          set -x
          mkdir artifact

          cd ..
          brew install libusb
          export PATH=$PATH:~/.cargo/bin
          if [[ ! -x $(command -v rustc) ]]; then
            curl -o rustup.sh https://sh.rustup.rs
            bash ./rustup.sh -y
          fi

          cd yubihsm-manager
          RUSTFLAGS="-C link-args=-Wl,-rpath,\$ORIGIN/../lib"  YUBIHSM_LIB_DIR=/usr/local/lib cargo build --release
          strip -u -r target/release/yubihsm-manager
          install target/release/yubihsm-manager artifact

          otool -L target/release/yubihsm-manager

          ./target/release/yubihsm-manager --version
          ./target/release/yubihsm-manager --help

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: yubihsm-manager-macos-${{ matrix.arch }}
          path: artifact

  Windows-Build:
    name: Windows
    runs-on: windows-latest
    env:
      LIBYUBIHSM_VERSION: 2.4.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # downloads and build yubihsm-shell from source release on dev.y.c
      - name: install yubihsm-shell
        run: |
          $ErrorActionPreference = "Stop"
          Set-PSDebug -Trace 1

          cd ..
          Invoke-WebRequest -Uri https://developers.yubico.com/yubihsm-shell/Releases/yubihsm-shell-$env:LIBYUBIHSM_VERSION-win64.msi -OutFile yubihsm-shell.msi -UseBasicParsing

          $log = "$env:GITHUB_WORKSPACE\install.log"
          $procMain = Start-Process "msiexec" "/i `"yubihsm-shell.msi`" /qn /l*! `"$log`"" -NoNewWindow -PassThru
          $procMain.WaitForExit()

      - name: clone yubihsmrs
        run: |
          $ErrorActionPreference = "Stop"
          Set-PSDebug -Trace 1

          cd ..
          git clone -b yubihsm-manager https://github.com/Yubico/yubihsmrs.git

      - name: Build yubihsm-manager
        run: |
          $ErrorActionPreference = "Stop"
          Set-PSDebug -Trace 1
          mkdir artifact
          
          $env:OPENSSL_LIB_DIR="C:\Strawberry\c\lib"
          $env:OPENSSL_INCLUDE_DIR="C:\Strawberry\c\include"
          $env:OPENSSL_DIR="C:\Strawberry\c"

          rustup target add x86_64-pc-windows-gnu
          rustup default stable-x86_64-pc-windows-gnu

          $env:RUST_BACKTRACE=1
          $env:YUBIHSM_LIB_DIR="C:\Program Files\Yubico\YubiHSM Shell\bin"
          #$env:PATH+=";C:\Program Files\Yubico\YubiHSM Shell\bin;C:\rtools43\x86_64-w64-mingw32.static.posix\bin"
          cargo.exe build --release 
          install target/release/yubihsm-manager $env:GITHUB_WORKSPACE/artifact/yubihsm-manager

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: yubihsm-manager-windows
          path: artifact
